version: '3.2'
services:

  api-php70:
    build:
      context: ./api-php70
    container_name: mcg-api-php70
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_API}
    volumes:
      - ${API_DIR}:/var/www/html
    networks:
      static-network:
    restart: always

  web-react:
    build:
      context: ./web-react
    container_name: mcg-web-react
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_WEB}
      - VIRTUAL_PORT=3000
    volumes:
      - ${WEB_DIR}/src:/srv/app/src
      - ${WEB_DIR}/public:/srv/app/public
    networks:
      static-network:
    restart: always

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24